const AppImages = {
LOGO: require('../images/Logo.png'),
USER: require('../images/user.png'),
LEFT: require('../images/left.png'),
HOME: require('../images/home.png'),
APPOINTMENT: require('../images/appointment.png'),
CALENDAR: require('../images/calendar.png'),
CALLBACK: require('../images/callback.png'),
MENU: require('../images/menu.png'),
BELL: require('../images/bell.png'),
EARN: require('../images/earn.png'),
HISTORY: require('../images/history.png'),
LOGOUT: require('../images/Logout.png'),
OFFER: require('../images/Offers.png'),
PRESCRIPTION: require('../images/prescrip.png'),
PROFILE: require('../images/profile.png'),
SETTING: require('../images/Settings.png'),
CARDLOGO: require('../images/cardlogo.png'),
PURCHASEIMG: require('../images/purchase.png'),
NEXT: require('../images/next.png'),
CLOCK: require('../images/clock.png'),
DOWN: require('../images/down.png'),
ROUND: require('../images/round.png'),
GOOGLE: require('../images/google.png'),
FACEBOOK: require('../images/facebook.png'),
EYE: require('../images/eye.png'),
EYECLOSE: require('../images/eyeclose.png'),
NULLIMAGE: require('../images/nullImage.jpg'),
PLACEHOLDER: require('../images/placeholder.png'),
}

export default AppImages;