export const RouteNames = {
  WelcomeScreen: 'WelcomeScreen',
  LoginScreen: 'LoginScreen',
  RegisterScreen: 'RegisterScreen',
  ForgotPasswordScreen: 'ForgotPasswordScreen',
  PasswordScreen: 'PasswordScreen',
  GuestLogin: 'GuestLogin',
  BottomTabs:'BottomTabs',
  HomeScreen: 'HomeScreen',
  AppointmentScreen: 'AppointmentScreen',
  CallBackScreen: 'CallBackScreen',
  Dashboard:'Dashboard',
  MyProfile: 'MyProfile',
  PrescriptionDetails: 'PrescriptionDetails',
  PurchaseHistoryList: 'PurchaseHistoryList',
  ReferNEarn: 'ReferNEarn',
  OfferScreen: 'OfferScreen',
  PurchaseHistoryDetails: 'PurchaseHistoryDetails',
  Purchase:'Purchase',
  ScheduleAppointment: 'ScheduleAppointment',
  ConfirmAppointment:'ConfirmAppointment',
  ConfirmRequest: 'ConfirmRequest',
  AppointmentListScreen:'AppointmentListScreen',
  SignUpPage: 'SignUpPage'
} as const;
